name: Test

on:
  push:
    branches: '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install requirements
        run: |
          pip install -e .
          pip install -r requirements-test.txt
      - name: Run pytest
        run: pytest
